server:
  name: router_service  # 服务名称
  port: 10000
  address: 127.0.0.1  # 服务地址

jwt:
  signing-key: 7ec8d27f-85f3-4d8c-9290-5e5fea2773f9
  expires-time: 7d
  buffer-time: 1d
  issuer: dousheng

logger:
  level: info
  prefix: '[dousheng]'
  director: log
  show_line: true
  log_in_console: true


etcd:
  address: 47.109.59.237:2379