server:
  name: user_service  # 服务名称
  address: 127.0.0.1:10001  # 服务地址


mysql:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: douyin

logger:
  level: info
  prefix: '[dousheng]'
  director: log
  show_line: true
  log_in_console: true

etcd:
  address: 127.0.0.1:2379

redis:
  address: 127.0.0.1:6379
  password: