server:
  name: router_service  # 服务名称
  port: 10002
  address: 127.0.0.1  # 服务地址
mysql:
  driver: mysql
  host: cfddfc.online
  port: 3306
  username: root
  password: 123456
  database: douyin

etcd:
  address: 127.0.0.1:2379

redis:
  address: 127.0.0.1:6379

logger:
  level: info
  prefix: '[video_service]'
  director: log
  show_line: true
  log_in_console: true
