server:
  name: video_service  # 服务名称
  address: 127.0.0.1:10002  # 服务地址


mysql:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: douyin

logger:
  level: info
  prefix: '[dousheng]'
  director: log
  show_line: true
  log_in_console: true

etcd:
  address: 127.0.0.1:2379

redis:
  address: 127.0.0.1:6379
  password:

rabbitMQ:
  user: guest
  password: guest
  address:  127.0.0.1:5672
  vhost:

oss:
  link: douyin.cfddfc.online
  bucket: microservice-v1
  accessKey: 1gvutSKAKY7cwPwwWkHDeQL8kX4iCuOxGvTMg2CT
  secretKey: emZSDHr6oi2C5eJzlMJMc50DryW415crhzOCLzPQ


